name: Lint, UT, Coverage, Quality

on:
    push:
        branches:
            - main
            - 'release/**'
        tags:
            - '*.*.*'

jobs:
    code-checks:
        runs-on: [self-hosted, macos]
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Bootstrap
              run: yarn bootstrap
            - name: Linter
              run: yarn lint
            - name: Unit Tests
              run: yarn test
            - name: Extract branch name
              shell: bash
              run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
              id: extract_branch
              # Yes, I'm too lazy to login into all the minions and install it manually. :)
              # Will leave this here for a week or so, until every minion has it installed
            # - name: install sonar-scanner
            #   run: arch -arm64 brew install sonar-scanner || brew install sonar-scanner
            # - name: Sonar Scanner
            #   run: sonar-scanner -Dsonar.branch.name=${{ steps.extract_branch.outputs.branch }} -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
