name: E2E Harness App (tvOS)

defaults:
    run:
        shell: zsh -l {0}
on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'release/**'
        paths-ignore:
            - 'docs/**'
            - '**/README.md'
    pull_request:
        types: [labeled]

jobs:
    e2e-harness-tvos:
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || github.event.label.name == 'e2e-harness-tvos' || github.event.label.name == 'e2e' }}
        runs-on: [self-hosted, macos]
        steps:
            - uses: actions/checkout@v2
            - name: Setup
              run: |
                  security unlock-keychain -p ${{ secrets.FLEXN_KEYCHAIN_PASSWORD }} Flexn.keychain
                  yarn config set network-timeout 300000
            - name: Bootstrap
              run: |
                  yarn bootstrap-clean
            - name: Build
              id: build
              run: |
                  cd packages/app-harness && yarn build:tvos-test
            - name: E2E DR1
              if: (success() || failure()) && steps.build.outcome == 'success'
              run: |
                  cd packages/app-harness && yarn e2e:tvos --spec ./test/specs/DR1.cjs
            - name: E2E G1
              if: (success() || failure()) && steps.build.outcome == 'success'
              run: |
                  cd packages/app-harness && yarn e2e:tvos --spec ./test/specs/G1.cjs
            - name: E2E L1
              if: (success() || failure()) && steps.build.outcome == 'success'
              run: |
                  cd packages/app-harness && yarn e2e:tvos --spec ./test/specs/L1.cjs
            - name: E2E NF1
              if: (success() || failure()) && steps.build.outcome == 'success'
              run: |
                  cd packages/app-harness && yarn e2e:tvos --spec ./test/specs/NF1.cjs
            - name: E2E PF1
              if: (success() || failure()) && steps.build.outcome == 'success'
              run: |
                  cd packages/app-harness && yarn e2e:tvos --spec ./test/specs/PF1.cjs
            - name: E2E R1
              if: (success() || failure()) && steps.build.outcome == 'success'
              run: |
                  cd packages/app-harness && yarn e2e:tvos --spec ./test/specs/R1.cjs
            - name: E2E RH1
              if: (success() || failure()) && steps.build.outcome == 'success'
              run: |
                  cd packages/app-harness && yarn e2e:tvos --spec ./test/specs/RH1.cjs
            - name: E2E SF1
              if: (success() || failure()) && steps.build.outcome == 'success'
              run: |
                  cd packages/app-harness && yarn e2e:tvos --spec ./test/specs/SF1.cjs
            # Commented because e2e tests would fail due to harness builds not working and minion issues
            # - name: Post message to Slack via Webhook
            #   if: ${{ github.event_name == 'push' && failure() }}
            #   uses: slackapi/slack-github-action@v1.23.0
            #   with:
            #       payload: |
            #           {
            #             "text": "<!here> *Harness tvOS e2e tests FAILED after* <${{ github.event.pull_request.html_url || github.event.head_commit.url }}|push> :alert:",
            #             "blocks": [
            #               {
            #                 "type": "section",
            #                 "text": {
            #                   "type": "mrkdwn",
            #                   "text": "<!here> *Harness tvOS e2e tests FAILED after* <${{ github.event.pull_request.html_url || github.event.head_commit.url }}|push> :alert:"
            #                 }
            #               }
            #             ]
            #           }
            #   env:
            #       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
