name: E2E Template App (Android)

defaults:
    run:
        shell: zsh -l {0}
on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'release/**'
        paths-ignore:
            - 'docs/**'
            - '**/README.md'
    pull_request:
        types: [labeled]

jobs:
    e2e-template-android:
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || github.event.label.name == 'e2e-template-android' || github.event.label.name == 'e2e' }}
        runs-on: [self-hosted, macos, intel]
        steps:
            - uses: actions/checkout@v2
            - name: Setup
              run: |
                  yarn config set network-timeout 300000
            - name: Bootstrap
              run: |
                  yarn bootstrap-clean
            - name: E2E Template App Android
              run: |
                  yarn e2e-template-android
            # Commented because e2e tests would fail due to minion issues
            # - name: Post message to Slack via Webhook
            #   if: ${{ github.event_name == 'push' && failure() }}
            #   uses: slackapi/slack-github-action@v1.23.0
            #   with:
            #       payload: |
            #           {
            #             "text": "<!here> *Template Android e2e tests FAILED after* <${{ github.event.pull_request.html_url || github.event.head_commit.url }}|push> :alert:",
            #             "blocks": [
            #               {
            #                 "type": "section",
            #                 "text": {
            #                   "type": "mrkdwn",
            #                   "text": "<!here> *Template Android e2e tests FAILED after* <${{ github.event.pull_request.html_url || github.event.head_commit.url }}|push> :alert:"
            #                 }
            #               }
            #             ]
            #           }
            #   env:
            #       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
